/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */
/*
 * Minimal kernel type definitions for BPF CO-RE programs.
 *
 * This header provides just the kernel struct definitions needed by
 * monitor.bpf.c. It is used in place of a full vmlinux.h generated by
 * `bpftool btf dump file /sys/kernel/btf/vmlinux format c`.
 *
 * To regenerate the full vmlinux.h (recommended for adding new tracepoints):
 *   bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
 *
 * These definitions must match the kernel's layout. CO-RE (Compile Once, Run
 * Everywhere) will relocate field offsets at load time via BTF, so exact
 * offsets here are not critical — only field names and types must match.
 *
 * References:
 *   - https://docs.kernel.org/bpf/btf.html
 *   - https://nakryiko.com/posts/bpf-core-reference-guide/
 */
#ifndef __VMLINUX_MINIMAL_H__
#define __VMLINUX_MINIMAL_H__

/* Standard kernel integer types expected by BPF programs. */
typedef unsigned char __u8;
typedef short unsigned int __u16;
typedef unsigned int __u32;
typedef unsigned long long __u64;
typedef signed char __s8;
typedef short int __s16;
typedef int __s32;
typedef long long __s64;

typedef __u8  u8;
typedef __u16 u16;
typedef __u32 u32;
typedef __u64 u64;
typedef __s8  s8;
typedef __s16 s16;
typedef __s32 s32;
typedef __s64 s64;

/* pid_t and other kernel typedefs. */
typedef int pid_t;
typedef unsigned int uid_t;
typedef unsigned int gid_t;

/* Network byte-order types used by BPF helper declarations.
 * These are needed by bpf_helper_defs.h even though we don't use
 * networking helpers. */
typedef __u16 __be16;
typedef __u32 __be32;
typedef __u64 __be64;
typedef __u32 __wsum;

/* Boolean type for BPF programs (kernel-style). */
typedef _Bool bool;
#define true  1
#define false 0

/* BPF map types (from include/uapi/linux/bpf.h).
 * We only define the ones we use. */
enum bpf_map_type {
    BPF_MAP_TYPE_HASH       = 1,
    BPF_MAP_TYPE_ARRAY      = 2,
    BPF_MAP_TYPE_PERF_EVENT_ARRAY = 4,
    BPF_MAP_TYPE_RINGBUF    = 27,
};

/* BPF map update flags (from include/uapi/linux/bpf.h). */
enum {
    BPF_ANY     = 0, /* Create or update element. */
    BPF_NOEXIST = 1, /* Create element only if it doesn't exist. */
    BPF_EXIST   = 2, /* Update element only if it exists. */
};

/*
 * task_struct — the kernel's process/thread descriptor.
 * We only declare the fields we actually read in BPF programs.
 * CO-RE will handle offset relocation at load time.
 */
struct task_struct {
    pid_t                pid;           /* Thread ID (TID) */
    pid_t                tgid;          /* Thread Group ID (what userspace calls PID) */
    struct task_struct  *real_parent;   /* Real parent process */
    struct task_struct  *group_leader;  /* Thread group leader */
    /* We access more fields via bpf_probe_read_kernel() as needed. */
};

/*
 * Tracepoint context structures.
 *
 * These are passed to tracepoint BPF programs as the first argument.
 * The field layout matches the kernel's tracepoint format strings
 * (see /sys/kernel/debug/tracing/events/<category>/<event>/format).
 */

/* syscalls/sys_enter_execve tracepoint args.
 * Format: field:const char * filename; field:const char *const * argv;
 *         field:const char *const * envp;
 * See: /sys/kernel/debug/tracing/events/syscalls/sys_enter_execve/format */
struct trace_event_raw_sys_enter_execve {
    /* Common tracepoint header fields (8 bytes padding). */
    unsigned long long __pad;
    long               __syscall_nr;
    const char        *filename;
    const char *const *argv;
    const char *const *envp;
};

/* syscalls/sys_exit_execve tracepoint args.
 * Format: field:long ret;
 * See: /sys/kernel/debug/tracing/events/syscalls/sys_exit_execve/format */
struct trace_event_raw_sys_exit_execve {
    unsigned long long __pad;
    long               __syscall_nr;
    long               ret;
};

/* sched/sched_process_exit tracepoint args.
 * Format: field:char comm[16]; field:pid_t pid; field:int prio;
 * See: /sys/kernel/debug/tracing/events/sched/sched_process_exit/format */
struct trace_event_raw_sched_process_exit {
    unsigned long long __pad;
    char               comm[16];
    pid_t              pid;
    int                prio;
};

#endif /* __VMLINUX_MINIMAL_H__ */
